name: Release Docker Image

on:
  release:
    types: [published]

jobs:

  release:
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout code
      uses: actions/checkout@master

    - name: Set environment variables
      run: |
        tag_name="${{ github.event.release.tag_name }}"
        echo "::set-env name=DOCKER_VERSION_TAG::itchyny/golang-simple-server-sample:${tag_name#v}"
        echo "::set-env name=DOCKER_LATEST_TAG::itchyny/golang-simple-server-sample:latest"

    - name: Build image
      run: |
        docker build -t "${DOCKER_VERSION_TAG}" .
        docker tag "${DOCKER_VERSION_TAG}" "${DOCKER_LATEST_TAG}"

    - name: Login to Registries
      run: docker login -u itchyny --password-stdin <<< "${{ secrets.DOCKER_HUB_TOKEN }}"

    - name: Push to Docker Hub
      run: |
        docker push "${DOCKER_VERSION_TAG}"
        docker push "${DOCKER_LATEST_TAG}"
