name: Release Docker Image

on:
  release:
    types: [published]

jobs:

  release:
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Set variables
      id: variables
      run: |
        git_tag_name="${{ github.event.release.tag_name }}"
        git_tag_name="${git_tag_name#v}"
        echo "::set-output name=release_tag_patch::${git_tag_name}"
        echo "::set-output name=release_tag_minor::${git_tag_name%.*}"
        echo "::set-output name=release_tag_major::${git_tag_name%%.*}"
        echo "::set-output name=created::$(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "::set-output name=repository_name::$(sed 's|.*/||' <<< ${{ github.repository }})"
        echo "::set-output name=repository_url::${GITHUB_SERVER_URL}/${{ github.repository }}"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: image=moby/buildkit:master

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and Release to DockerHub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ${{ github.repository }}:latest
          ${{ github.repository }}:${{ steps.variables.outputs.release_tag_patch }}
          ${{ github.repository }}:${{ steps.variables.outputs.release_tag_minor }}
          ${{ github.repository }}:${{ steps.variables.outputs.release_tag_major }}
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ steps.variables.outputs.release_tag_patch }}
          ghcr.io/${{ github.repository }}:${{ steps.variables.outputs.release_tag_minor }}
          ghcr.io/${{ github.repository }}:${{ steps.variables.outputs.release_tag_major }}
        labels: |
          org.opencontainers.image.title=${{ steps.variables.outputs.repository_name }}
          org.opencontainers.image.url=${{ steps.variables.outputs.repository_url }}
          org.opencontainers.image.source=${{ steps.variables.outputs.repository_url }}
          org.opencontainers.image.version=${{ github.event.release.tag_name }}
          org.opencontainers.image.created=${{ steps.variables.outputs.created }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.licenses=${{ github.event.repository.license.name }}
